services:
  remnawave-db:
    image: postgres:17
    container_name: 'remnawave-db'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=remnawave
      - TZ=UTC
    ports:
      - '5437:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  remnawave-redis:
    image: 'redis:alpine'
    container_name: remnawave-redis
    volumes:
      - redis:/data
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - '127.0.0.1:6379:6379'
    restart: always
    environment:
      - TZ=Europe/Moscow
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2000M'

volumes:
  redis:
    name: remnawave-redis
