name: Deploy backend contracts
on:
  push:
    branches: ['**']
    paths:
      - 'libs/**/package.json'
      - '.github/workflows/deploy-lib.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies and build
        working-directory: 'libs/contract'
        run: npm i && npm run prepublish

      - name: Publish package on NPM
        working-directory: 'libs/contract'
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  send-telegram-message:
    name: Send Telegram message
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Send Telegram message
        uses: proDreams/actions-telegram-notifier@main
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          thread_id: ${{ secrets.TELEGRAM_TOPIC_ID }}
          status: success
          notify_fields: 'repository,branch,commit,workflow'
          title: 'Deploy contract finished with status:'

  notify-on-error:
    runs-on: ubuntu-latest
    needs: [build]
    if: failure()
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Send Telegram message
        uses: proDreams/actions-telegram-notifier@main
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          thread_id: ${{ secrets.TELEGRAM_TOPIC_ID }}
          status: failure
          notify_fields: 'repository,branch,commit,workflow'
          title: 'Deploy contract failed with status:'
